const PRIMARY_COLOR = 'rgb(52,116,235)';

export const theme = {
  folderColor: '#e8b10c',
  fileColor: '#b0aeae',
  fileDescriptionColor: '#969696',
  fileTitleColor: '#3d3d3d',
  negativeColor: '#fff',
  mediumText: 'OpenSans-Medium',
  regularText: 'OpenSans-Regular',
  strongText: 'OpenSans-Bold',
  musicalFileColor: '#eb4034',
  pdfFileColor: '#3169e0',
  docFileColor: '#3169e0',
  xlxFileColor: '#30b516',
  archiveFileColor: '#dba50f',
  fileMenuColor: '#ababab',
  filePathColor: 'rgb(235, 235, 235)',
  selectionColor: PRIMARY_COLOR,
  selectionNotCompleteColor: 'grey',
  selectionIconSize: 25,
  toggleBgColor: 'rgba(150, 150, 250, 0.1)',
  toggleBtnWidth: 20,
  toggleBtnHeight: 37,
  radiusPrimary: 10,
  radiusMedium: 4,
  primaryLoaderSize: 60,
  sizes: {
    NO_DATA_ICON: 40,
    HEADER_ICON: 25,
    HEADER_TITLE_FONT: 20,
  },
  layout: {
    GRID_WIDTH_BASE: 100,
    GRID_HEIGHT: 110,
    LIST_HEIGHT: 70,
  },
  dialogContainer: {
    borderRadius: 5,
    backgroundColor: '#fafafa',
  },
  inputContainer: {
    backgroundColor: '#f0f0f0',
    color: PRIMARY_COLOR,
  },
};
